network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      addresses:
        - 192.168.65.10/24
      routes:
        - to: 192.168.75.0/24
          via: 192.168.75.101
        - to: 192.168.60.0/24
          via: 192.168.65.100